### PR TITLE
Allow multiple grids with different gutters

### PR DESCRIPTION
**Pull request by hooddanielc**
This pr generates a uuid in the grid component className and uses that class in css selectors. This allows multiple grids to be on the same page with different gutters.

### CODE REVIEW

**Comment by skiano** [comment]
This is interesting :)

I have a few questions:

- What is the advantage of creating a uuid vs incrementing a global id (ie grid-1, grid-2, grid3, ...)
- If we do use a uuid, won't we cause an invariant error for users who are rendering on the backend?
- What is the addition of node-gyp for? I am not familiar with that

Thanks for the pr!

**Comment by hooddanielc** [comment]
Thanks for responding to my pr. I really like this project and find it to be a great solution for what I'm trying to do.

- I think incrementing will work better and shouldn't be a problem. I've changed it to use the current `breakCount` variable on the grid class instead of generating a uuid.

- I thought I needed node-gyp because one of the deps tried to recompile a native addon when it couldn't find the binary for the current installed version. I downgraded to stable version everything worked fine. I removed node-gyp from package.json

**Comment by skiano** [comment]
The break count probably shouldn't be used for a couple reasons. The first is that it is a temporary solution to a bug inside react that prevents context changes being updated in components that use shouldcomponentupdate. The second is that it changes based on your screen changing size, not based on new grids being made (break refers here to how many times the size has changed pass the breakpoint thresholds)

Maybe we should just add a new value that is incremented in the constructor for the grid component?

Maybe something like:

```javascript
// inside grid.js
let gridId = 0;

// inside grid constructor
constructor (props) {
  this.gridId = gritId++;
}


```

**Comment by skiano** [comment]
Ok, one last picky thing. I really think the ` this.gridId = gridId++;` should be in the constructor, because `render` will fire every time the component updates. Is there some reason you want each grid's id to change every time an update occurs?

BTW, thanks for adding tests :)

**Comment by hooddanielc** [comment]
Yep, you are right. Thank you. I've moved it to the constructor and tested manually.

**Comment by skiano** [comment]
Ok, great :)

I will pull it down and confirm. Then I will look at publishing it. I will probably do a major version bump, just because I haven't released in so long.

**Comment by hooddanielc** [comment]
Ya that would look good :)

**Comment by hooddanielc** [comment]
What also might look good is bumping the version of reactjs to latest stable version.

**Comment by skiano** [comment]
For sure, I'm sure everything is way out of date

**Comment by skiano** [comment]
I am looking at getting the dependencies up to date, and it may take me some time. (now i see what happened with node-gyp for you)

**Comment by skiano** [comment]
I think after taking a look, it looks pretty urgent to upgrade things.
I started an issue here: https://github.com/dowjones/react-cellblock/issues/13

I'm not sure how fast I can do it, and I apologize for the delay

**Pull request merged**
