### PR TITLE
Upgrade the world

### PR DESCRIPTION
**Pull request by hooddanielc**
Upgrade React
Upgrade Webpack
Upgrade Babel
Modify source code to be compiled by babel 6

This pr is in response to https://github.com/dowjones/react-cellblock/issues/13 . This will get you most of the way to upgrading deps. webpack dev server works great, but I could not fix the tests because I ran out of time for the day and am not familiar with the way tools are being used here. I suggest allowing your code work with only the `babel-preset-es2015` and `babel-preset-react` options in .eslintrc. Feel free to work off of this or make a new pr.

Hope this helps,

Thanks

### CODE REVIEW

**Comment by skiano** [comment]
Thanks so much!

This is further than I was last night, so I will start from here

**Comment by hooddanielc** [comment]
@skiano I figured out why tests were not running. Fixing it was as simple as adding `-r test/_helpers/boot` flag. There is only 1 test failing and a few deprecations and messages I'm currently not sure how to fix. The messages are below.

`src/util/validators.js`

I'm assuming this message should not show up here.

```
    Server Rendering
Warning: Failed prop type: Isomorphic grids require an initialBreakpoint
    in Grid
      ✓ should use default to infinite screen size
```

`src/util/validators.js`

It looks like PropTypes is deprecating the ability to manually call a prop type. The only information I could find relating to testing PropTypes is by overriding console.log and checking the last message that was logged.

```
  Grid Type Validation
Warning: You are manually calling a React.PropTypes validation function for the `prop` prop on `<<anonymous>>`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `prop` prop on `<<anonymous>>`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: Invalid argument supplied to oneOf, expected an instance of array.
    1) validBreakpoint
```

It appears that once these are fixed, #13 will be complete

**Comment by hooddanielc** [comment]
I upgraded istanbul and mocha. The test-coverage check runs almost instantly.

**Comment by skiano** [comment]
I figured out the deprecation warning on my end

Its this line:
https://github.com/dowjones/react-cellblock/blob/master/src/util/validators.js#L16

I think we can just change that line to:
```javascript
return p => props.breakpoints.includes(p);
```

Which seems nicer anyway

**Comment by skiano** [comment]
I am going to just merge this into master, and we will deal with the last few things separately

**Comment by skiano** [comment]
Thanks again by the way! This was super helpful.

**Comment by skiano** [comment]
The only two things i changed about this were cleaning up some of the exports:
https://github.com/dowjones/react-cellblock/commit/cfc5865d1f3cd98338cce93c6a727528af16ea3a

And fixing the last couple of tests / the deprecation warning you mentioned:
https://github.com/dowjones/react-cellblock/commit/4bdc34bd01e54e483f9789cd377aee2550c55a05

**Pull request merged**
